theme: jekyll-theme-minimal
title: WearFamily Documentation
description: Documentation for the WearFamily e-commerce platform
baseurl: "/FSD04_WebDev1_WearFamily_deployed"
url: "https://xuanwgit.github.io"
show_downloads: true
google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 